<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Reminder_model extends CI_Model
{

    public $table = 'reminder';
    public $id = 'id_reminder';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_reminder', $q);
	$this->db->or_like('customer_code', $q);
	$this->db->or_like('invoice_date', $q);
	$this->db->or_like('amount_total', $q);
	$this->db->or_like('remark', $q);
	$this->db->or_like('email1', $q);
	$this->db->or_like('email2', $q);
	$this->db->or_like('top', $q);
	$this->db->or_like('invoice_number', $q);
	$this->db->or_like('handphone', $q);
	$this->db->or_like('invoice_due_date', $q);
	$this->db->or_like('status', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        if ($this->session->userdata('level') !='admin') {
            $this->db->where('user', $this->session->userdata('id_user'));
        }
        $this->db->like('invoice_number', $q);
 //        $this->db->or_like('user', $this->session->userdata('id_user'), 'after');
	// $this->db->or_like('customer_code', $q);
	// $this->db->or_like('invoice_date', $q);
	// $this->db->or_like('amount_total', $q);
	// $this->db->or_like('remark', $q);
	// $this->db->or_like('email1', $q);
	// $this->db->or_like('email2', $q);
	// $this->db->or_like('top', $q);
	// $this->db->or_like('invoice_number', $q);
	// $this->db->or_like('handphone', $q);
	// $this->db->or_like('invoice_due_date', $q);
	// $this->db->or_like('status', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Reminder_model.php */
/* Location: ./application/models/Reminder_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2019-12-01 05:03:54 */
/* http://harviacode.com */